### ISSUE TITLE
CC with spaces causing trouble?

### ISSUE THREAD

**Issue by rofl0r** [arsv/perl-cross#112]
```
Configuring primary perl executable for i486-linux-musl (i486-pc-linux-musl)
Checking perl version ... perl5-5.34.0
Checking for cc ... ERROR: Supplied i486-linux-musl-gcc -L/home/ubuntu/x-prefix/i486/lib -isystem /home/ubuntu/x-prefix/i486/include is not usable
ERROR: configure --mode=target failed
```

could it be that shell executes `"$CC"` instead of `$CC` (without quotes) and causes this issue ?
i used `CC="486-linux-musl-gcc -L/home/ubuntu/x-prefix/i486/lib -isystem /home/ubuntu/x-prefix/i486/include" ./configure --target=i486-linux-musl`

**Comment by arsv** [comment]
Yes that's exactly what happens. https://github.com/arsv/perl-cross/commit/443f7bd08b19e71a2e838dcb6cde176998cd350f

configure --with-cc= skips that check and everywhere else it's just $(CC) effectively.

**Comment by rofl0r** [comment]
thanks!
