### ISSUE TITLE
perl-5.20.2 on Buildroot

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#13]
with Perl 5.20.2, another workaround is required see http://git.buildroot.net/buildroot/commit/package?id=8a4c8deee9af6fa1a1e906c52d7d49a32434464c

see failure at http://autobuild.buildroot.net/results/1c2/1c261b09f5a4a314d5dcbc1e5811af9c7d18658a/build-end.log

currently, Buildroot uses perl-cross 0.9.4, but 0.9.5 doesn't solve the issue.

**Comment by arsv** [comment]
https://github.com/arsv/perl-cross/commit/b386b1b279980b8146cae84d195cb5999237bd44

Please test it if possible, and I'll tag it 0.9.6 so that buildroot could use it.

**Comment by fperrad** [comment]
The new `x2p/Makefile` works fine. Thanks.

**Comment by arsv** [comment]
Ok, tagged 0.9.6.
