### ISSUE TITLE
Enabling multiplicity

### ISSUE THREAD

**Issue by leahneukirchen** [arsv/perl-cross#135]
Is it possible to enable `-DMULTIPLICITY` by any flag? `USE_ITHREADS` is set by default, but for mod_perl we also need `MULTIPLICITY`. I think the upstream Perl configure enables both with `-Dusethreads`.

**Comment by arsv** [comment]
`configure ... --use-multiplicity`

I see that logic in mainline Configure and I'm going to add it to perl-cross as well, so starting with the next tagged version there will be no need to enable it explicitly.

**Comment by leahneukirchen** [comment]
Fixed in a31a5cddd6c52fd21976b9cbff303b966c4a3122
