### ISSUE TITLE
0.9.6 release "broken"

### ISSUE THREAD

**Issue by moben** [arsv/perl-cross#14]
Not broken as such, but you didn't actually gzip it, so the .tar.gz extension is a bit misleading.

On a related note: Github allows uploading release tarballs alongside a tag for a while now, would you consider using that instead of a branch of tarballs? Then the downloads would be in the expected place.

**Comment by arsv** [comment]
Oh. Fixed.

No problem, tags updated for 0.9.x, you can use that if you like.
I wasn't aware of this feature, the last time I checked releases were strictly tag snapshot and that didn't work well with perl-cross.

**Comment by moben** [comment]
Thanks, I switched us over to the new urls.
