### ISSUE TITLE
Add -D_GNU_SOURCE to HOSTCFLAGS

### ISSUE THREAD

**Issue by vimproved** [arsv/perl-cross#142]
Currently, the cross compilation is failing on a musl host due to setresuid and setresgid only being available if _GNU_SOURCE is defined. Any chance `-D_GNU_SOURCE` could be added to HOSTCFLAGS in Makefile.config.SH?

**Comment by arsv** [comment]
./configure --host-set-ccflags=-D_GNU_SOURCE --target=...
