### ISSUE TITLE
fail with  perl-5.22.0 and static build

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#18]
see patch/discussion on Buildroot https://patchwork.ozlabs.org/patch/517172/

**Comment by fperrad** [comment]
the [patch](http://git.buildroot.net/buildroot/plain/package/perl/0001-fix-EUMM.patch) which fixes the issue in __Buildroot__, is not needed when building a native __Perl__ (without __perl-cross__)
```
$ ./Configure -des -Uusedl
$ make
```

So, may be, the issue could be fixed in __perl-cross__ instead of in __perl__.

**Comment by fperrad** [comment]
the patch is enough with a Buildroot external toolchain, but not with http://autobuild.buildroot.org/toolchains/tarballs/br-arm-full-static-2015.08-rc1-38-gad0f85e.tar.bz2

see http://autobuild.buildroot.net/results/f1b/f1b887781655c47e8a637a2df2a8029ef439083a/

**Comment by arsv** [comment]
Ok, here's what fixes that vpp.pm issue:
https://github.com/arsv/perl-cross/commit/f53a9f1b613b84396d174855f6c37bf04f76bae3

The original perl makefiles let miniperl use any module under lib/, so it successfully picks up the right version.pm.
In perl-cross without that fix, version.pm is not available, so at lib/ExtUtils/MakeMaker/version.pm:24 they attempt to substitute some kind of fall-back stub for version.pm. Which happens to be more demanding that the actual version.pm.

Missing Bessel functions are almost for sure unrelated to this. I can't see them in libm.a from that toolchain, but it looks like configure detects them as available.

**Comment by arsv** [comment]
And libm.a link tests fixed as well:
https://github.com/arsv/perl-cross/commit/ce7fa56d3a40767135039e03517a4d9ef2f3aaa1

**Comment by fperrad** [comment]
sounds good.
