### ISSUE TITLE
Incorrect arsv.github.io Download URL

### ISSUE THREAD

**Issue by abelbeck** [arsv/perl-cross#21]
The ever changing GitHub download url's makes the link on:

http://arsv.github.io/perl-cross/download.html

incorrect, this download link works for me with ```wget```

https://github.com/arsv/perl-cross/releases/download/1.0.2/perl-5.22.1-cross-1.0.2.tar.gz

**Comment by arsv** [comment]
Och. Fixed, thanks for noticing.
