### ISSUE TITLE
Check for d_sockaddr_in6

### ISSUE THREAD

**Issue by chneukirchen** [arsv/perl-cross#26]
Some d_* default to undef, but there is no check to enable them.

At least for d_sockaddr_in6, this results in missing code in IO::Socket related to handling IPv6 addresses, and checking for it should be easy.

**Comment by arsv** [comment]
Done, d_sockaddr_in6 should be properly defined now.
If possible, please check it in your setup.

**Comment by chneukirchen** [comment]
Makefile.config.SH still contains one bashism `==` in line 52.

Check works, thanks!

**Comment by arsv** [comment]
And another one on line 44. Fixed, thanks for noticing!
