### ISSUE TITLE
fix cpan/ExtUtils-Constant/t/Constant.t

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#32]
This RT ticket https://rt.cpan.org/Public/Bug/Display.html?id=88645 is 3 years old.
But this module `ExtUtils-Constant` seems abandonned.

Could you add in `perl-cross`, this patch https://rt.cpan.org/Ticket/Attachment/1266165/670409/perl-cross-EUC-V2.patch

**Comment by arsv** [comment]
Sure, added patches for both mainline versions.
Cperl apparently dropped this module altogether.
