### ISSUE TITLE
install cperl as perl

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#38]
Currently with perl-cross, the target `install.perl` installs `cperl5.24.0`  and `cperl` as a full copy. So there is no `perl`.

In native way, `perlbrew install cperl-5.24.0` installs `cperl5.24.0` and creates 2 symbolic links `cperl` and `perl`.
I think it's a better job.

**Comment by arsv** [comment]
perl symlink added.

And I made it remove the versioned executable ("perl5.24.0"), leaving only the non-versioned one ("perl" or "cperl"). Those are hardlinks, not copies, but that's still not good, and I can't see any reason to leave the versioned executable around. Current scripts are not capable of installing two versions with the same prefix anyway.

**Comment by fperrad** [comment]
I think that I've found the origin of the difference of behaviour.
`perlbrew` does only a specific thing with `cperl`, it adds `-Dusecperl` in configure options.
All installation process is done by `installperl` from the cperl distribution.
With `perlbrew` (for perl or cperl), `installperl` is called with `--destdir=`.
But with Buildroot + cross-perl, `destdir` is not empty.
And the `ìnstallperl` of cperl seems not mature about `destdir`.

I try this patch https://github.com/fperrad/cperl/commit/ff52451c406a21f5fa541fcc055ba993cb9a5d52
but it looks like the `link` of `miniperl` acts as a full copy.

**Comment by arsv** [comment]
I'm pretty sure the linking is done externally to `installperl` in perlbrew
https://github.com/gugod/App-perlbrew/blob/d160bfc456ec80e04542bd3ee96f18ddecdf431d/perlbrew#L2059-L2060
At least that's what I was looking at before going on and adding ln -s to Makefile.

Though that part in installperl looks interesting, checking.

**Comment by fperrad** [comment]
You are right. Symlinks are done by `perlbrew`.
With Buildroot + perl-cross + perl, the target `install.perl` installs `perl5.24.0` and `perl` as a full copy.
So the target `install.sym` could be useful for both cperl and perl distributions.

This implementation works in both case:
```make
install.sym:
	ln -sf $(perlname)$(version) $(DESTDIR)$(installbin)/$(perlname)
	ln -sf $(perlname)$(version) $(DESTDIR)$(installbin)/perl
```

**Comment by arsv** [comment]
Oh. I was sure I pushed that last change but I didn't. Please check it now.
The idea is to keep `perl` executable as a proper file, not as a symlink, and drop `perl5.24.0`.
For cperl, the sole executable will be `cperl` (no version) and `perl` will be a symlink to `cperl`.

**Comment by fperrad** [comment]
I prefer all custom stuff in the new target `install.sym`, see https://github.com/fperrad/perl-cross/commit/6792cf8d22aea518e38a6697bffcf6fbd1b1127d

**Comment by arsv** [comment]
Makes sense, patch merged.

**Comment by fperrad** [comment]
It seems we are ready for a new tag.
Just before, you could bump to perl 5.25.5

**Comment by arsv** [comment]
Sure, bumped 5.25 to 5.25.5, replacing 5.25.4.
