### ISSUE TITLE
Can't compile perl 5.22.3

### ISSUE THREAD

**Issue by kentfredric** [arsv/perl-cross#46]
Relaying from downstream: https://bugs.gentoo.org/608428

There's no apparently way currently to cross-compile compile perl 5.22.3

Latest version 1.1.1 fails, as does older version 1.0.2

Its not clear what support policies are in place for this, given 5.22.x  is still what we consider to be "the stable branch"

**Comment by arsv** [comment]
Looks like 5.22.1 was the last supported 5.22.x, then it was all 5.24.
And perl-cross could only support one perl version back then.

Anyway, patches added, looks like everything builds well.
Please check https://github.com/arsv/perl-cross/tree/perl-5.22 branch if possible, and I'll merge it.

**Comment by kentfredric** [comment]
Confirming that at least, 1.1.4 appears to fix cross compile for 5.22.3 :)
