### ISSUE TITLE
Build without zlib and bzip2

### ISSUE THREAD

**Issue by protonesso** [arsv/perl-cross#63]
Hi, asvr! I use your "perl-cross" and I want to build perl with perl-cross, but without zlib and bzip2.

Thanks.

**Comment by arsv** [comment]
Try building it like this:

    ./configure --disable-modules cpan/Compress-Raw-Bzip2,cpan/Compress-Raw-Zlib

Perl itself does not need any compression libraries.

**Comment by protonesso** [comment]
Thanks!
