### ISSUE TITLE
Request to update config.guess and config.sub

### ISSUE THREAD

**Issue by selkfoster** [arsv/perl-cross#81]
Please, update the config.guess and config.sub files for the cnf/ directory provided by perl-cross:

You can find it at http://git.savannah.gnu.org/gitweb/?p=config.git;a=tree

This will help to detect for example based targets on the Musl libc, let's say:
armv7hl-linux-musleabihf

Thanks for you work on perl-cross.

**Comment by arsv** [comment]
Updated.

**Comment by selkfoster** [comment]
Good.  :-)
