### ISSUE TITLE
perl is built with . in INC by default

### ISSUE THREAD

**Issue by stigtsp** [arsv/perl-cross#98]
`default_inc_excludes_dot` defaults to `undef` when building cross building perl, not sure if this is intentional.

`-Ddefault_inc_excludes_dot` is needed to avoid this in https://github.com/NixOS/nixpkgs/pull/98466

**Comment by arsv** [comment]
Updated to match current mainline perl.

For some reason, it was "define" for cperl but "undef" for regular perl.
Most likely matching respective defaults at the time it was added.

https://github.com/arsv/perl-cross/blob/c2707f403df9fa6c718efb9f03b02fc6b7c9d4ff/cnf/configure_version.sh#L60

**Comment by stigtsp** [comment]
@arsv thx for quick fix! :+1:
